name: nightly-reminder
on:
  schedule:
    - cron: "* 20 * * 1-5"
jobs:
  reminder:
    name: reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make
      - run: ./bin/timecamper -tctoken $TC_TOKEN -slacktoken $SLACK_TOKEN -users $EMAILS
        env:
          TC_TOKEN: ${{ secrets.TC_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          EMAILS: ${{ secrets.EMAILS }}
